language: r
cache: packages
warnings_are_errors: true

# Test on multiple dists with every flavor of R
# limit to 5 instances for regular usage.  (5 can be done in parallel)
jobs:
  include:
    - &bionic
      name: Linux - bionic - oldrel
      os: linux
      dist: bionic
      r: oldrel
      if: |
        repo = meztez/redoc AND
        type = push AND
        branch IN (master)
    - <<: *bionic
      name: Linux - bionic - release
      r: release
      if: |
        true
    - <<: *bionic
      name: Linux - bionic - devel
      r: devel

    - &osx
      name: macOS - oldrel
      os: osx
      brew_packages: libsodium
      r: oldrel
      if: |
        repo = meztez/redoc AND
        type = push AND
        branch IN (master)
    - <<: *osx
      name: macOS - release
      r: release
      if: |
        true
    - <<: *osx
      name: macOS - devel
      r: devel
